name: PR Label Notification
on:
  pull_request:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Checks
        id: get-checks
        uses: actions/github-script@v6
        with:
          script: |
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });
            
            const failedChecks = checks.check_runs.filter(check => 
              check.conclusion === 'failure' || check.conclusion === 'cancelled' || 
              check.conclusion === 'timed_out' || check.conclusion === 'action_required'
            );
            
            const failedChecksMessage = failedChecks.length > 0 
              ? failedChecks.map(check => 
                  `• ${check.name}: ${check.conclusion} (${check.html_url})`
                ).join('\n')
              : 'No failed checks';
              
            core.setOutput('failed-checks', failedChecksMessage);
            core.setOutput('has-failures', failedChecks.length > 0 ? 'true' : 'false');

      - name: Send Slack notification
        if: github.event.label.name == 'migration' # Replace with your label name
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C06ADGRE2LQ' # Replace with your channel ID
          slack-message: |
            🔔 *New migration PR labeled!*
            
            *Title:* ${{ github.event.pull_request.title }}
            *Author:* ${{ github.event.pull_request.user.login }}
            *Label Added:* ${{ github.event.label.name }}
            
            *Description:*
            ${{ github.event.pull_request.body }}
            
            *Changes Overview:*
            - Base Branch: `${{ github.event.pull_request.base.ref }}`
            - Number of Changes: ${{ github.event.pull_request.changed_files }} files
            
            *CI Status:*
            ${{ steps.get-checks.outputs.has-failures == 'true' && '⚠️ Failed Checks:' || '✅ All checks passing' }}
            ${{ steps.get-checks.outputs.failed-checks }}
            
            *Links:*
            • <${{ github.event.pull_request.html_url }}|View Pull Request>
            • <${{ github.event.pull_request.html_url }}/files|View Changes>
            • <${{ github.event.pull_request.html_url }}/checks|View All Checks>
            
            Please Review @infra-on-call-text
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
